uc-cdis/gen3.org

config.yaml
Changed links in the footer that returned 404 error
=> PXP-2324 fix(link): Changed links that returned 404 error

content/community/webinars.md
- Change "servcies" to "services"
=> Fix typo on webinar page

config.yaml, content/resources/operator/_index.md
Added section about programs and projects
=> PXP-2589 docs(programs-projects): Added section about programs and projects

config.yaml, content/resources/operator/_index.md
- changed information about baseline dictionary
- added information about programs/projects
=> docs(dcfdictionary): DCF dictionary is a tempalate/baseline dictionary for creating new dictionaries

config.yaml, content/_index.md
This PR fulfills https://ctds-planx.atlassian.net/browse/PXP-4620
Changing the Demo commons URL to https://caninedc.org/
Can verify at http://alpha.gen3.org/
=> PXP-4620 chore(demo): demo url change

content/resources/user/gen3-client.md
changed mentions of upload/download "manifest" to "multiple" since the name change.
=> changed download-manifest to download-multiple

config.yaml, content/resources/_index.md, content/resources/user/query-data.md
=> adding docs for user graphQL

content/resources/user/gen3-client.md
=> gen3-client updates

content/resources/user/using-api.md
=> fixed link in user docs

content/resources/operator/_index.md
Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-6529)
- fixed quick link for the operator menu
=> fixed quicklink for operator page gen3.org

content/resources/user/template-tsvs.md
Docs had outdated information about formatting links in TSVs.
=> updated links specs

content/resources/developer/_index.md
"Juypter" changed to "Jupyter" in developer-intro
=> fixed typo

content/_index.md, content/get-started.md
facelift to gen3.org based on 2021 overview: https://docs.google.com/document/d/1NinAx8DgKox_7Vup1pXXfxVAXtwtAVrGnvtWjbbLMFk/edit#heading=h.k2ftb1zif9d
=> updates to 'About' page

content/resources/user/_index.md, content/resources/user/access-data.md
- fixed hot link
- removed link to OCC support email help desk
=> fix-links on resources/user and access-data

.travis.yml, config.yaml
- Install asciidoctor in CI to support asciidoc files
=> Support asciidoc files

content/community/events.md, content/community/events/gen3forum_20230301.md
Minor updates to March 1 Gen3 Forum website
=> update to agenda

content/powered-by-gen3.md
Remove ACCOUNT commons which was decommissioned in Feb 2022
=> Remove ACCOUNT commons

content/community/events.md, content/community/events/gen3forum_202210_post.md, layouts/shortcodes/events.html
=> Updates to add video and links to Oct 2022 Gen3 Forum

content/community/events.md, layouts/shortcodes/events.html
Added draft updates to the gen3 events page
=> Added Upcoming events

content/community/events.md
Move helm forum office hours to past event
=> Move helm forum office hours to past event

content/community/events.md
Data Mesh Community Forum Event
=> Data Mesh Community Forum Event

content/community/events.md
=> Added upcoming event - Gen3 Forum for Data Models

config.yaml, content/resources/gen3-features.md
Jira Ticket:  [PXP-10989](https://ctds-planx.atlassian.net/browse/PXP-10989)-   Add Feature links for MDS, AggMDS, Crosswalk and clean up organization of page
[PXP-10989]: https://ctds-planx.atlassian.net/browse/PXP-10989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update Gen3 Features

content/community/events.md
=> Post Gen3 Forum Data Modeling Video

.secrets.baseline, content/resources/user/analyze-data/Gen3_authentication.html, content/resources/user/analyze-data/notebook2_canine.html, content/resources/user/analyze-data/notebook3_gen3datacommonsio.html, nginx.conf
Jira Ticket: [PXP-10691](https://ctds-planx.atlassian.net/browse/PXP-10691)
- [add X-Frame-Options security header](https://github.com/uc-cdis/gen3.org/commit/9150d62165dcccfb4911cf391c91360ba80b0de9)
- [PXP-10691: remove unused css include](https://github.com/uc-cdis/gen3.org/commit/4880f98eef5dcfb8f0fd13bd2e851bb1f6e8d657)
- [PXP-10691: remove unused jquery](https://github.com/uc-cdis/gen3.org/commit/03ff5c4caba4ad1e047b70fa13e3ae49c766c050)
[PXP-10691]: https://ctds-planx.atlassian.net/browse/PXP-10691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> (PXP-10691): Fix/vulnerabilities

content/resources/user/_index.md
changed cdis@uchicago.edu to ctds@uchicago.edu
=> Update CTDS email

content/community/events.md, content/community/events/gen3forum_20230906.md, content/gen3-tools.md
=> Update community events and gen3 tools pages

content/community/events.md
=> update gen3.org with new forum video

config.yaml, content/gen3refs.md
This will have to be updated periodically
=> Create Gen3 Refs Page

content/_index.md
Jira Ticket: [PXP-1121](https://ctds-planx.atlassian.net/browse/PXP-11221) Remove Reference to IBDGC
n/a
n/a
n/a
- Remove reference to IBDGC
n/a
n/a
[PXP-1121]: https://ctds-planx.atlassian.net/browse/PXP-1121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove reference to IBDGC

config.yaml, content/governance.md
=> Steering committee page

config.yaml, content/community/_index.md
* Updating community page
consolidated some helpful links on the community page removed the Gen3 forum
* Update _index.md
* Replace Gen3 Forum
Replaced Gen3 Forum and renamed as discussion board
=> Updates to Community Page (#226)

content/community/events.md
Updating events page to include new video from the Gen3 Forum event on Gen3.2
=> Update events page

content/community/_index.md, content/resources/developer/_index.md, content/resources/operator/_index.md
Updating helm and cloud automation sections as well as reformatting other content on the page.
=> Update operator instructions

content/community/events.md
=> add slides

content/resources/operator/_index.md
Link to JIRA ticket if there is one: 
- Fixes link to the user.yaml guide
=> Fix user.yaml_guide link

content/powered-by-gen3.md, content/resources/user/_index.md, content/resources/user/analyze-data.md, content/resources/user/gen3-client.md
update all support emails from <whatever-support>@datacommons.io to <whatever-support>@gen3.org
Also update example emails in script output from user@datacommons.io or user@datacommons.org to user@gen3.org.
=> Update email datacommons - email

gen3/docs/index.md, gen3/docs/resources/user-guide/overview.md
=> A few more mkdocs updates

gen3/docs/gen3-resources/operator-guide/gen3-authn-methods.md, gen3/docs/gen3-resources/operator-guide/prerequisites.md
=> updated prerequisites and authentication sections for operator's guide

gen3/docs/about/powered-by-gen3.md, gen3/docs/resources/user-guide/analyze-data.md, gen3/docs/resources/user-guide/img/analyze-data.md, gen3/docs/resources/user-guide/img/gen3-client.md
update support email from @datacommons.io to @gen3.org
=> Update support email

.secrets.baseline, gen3/docs/gen3-resources/operator-guide/helm/helm-config-auth.md, gen3/docs/gen3-resources/operator-guide/helm/helm-config-data-svcs.md, gen3/docs/gen3-resources/operator-guide/helm/helm-config-frontend.md, gen3/docs/gen3-resources/operator-guide/helm/helm-config-revproxy.md, gen3/docs/gen3-resources/operator-guide/helm/helm-config-workspaces.md, gen3/docs/gen3-resources/operator-guide/helm/helm-deploy-databases.md, gen3/docs/gen3-resources/operator-guide/helm/helm-deploy-overview.md
flesh out new Helm docs using content from existing docs. 
Note: I had to update the secrets baseline, so that is included in the PR.
=> add content to additional Helm docs

.secrets.baseline, gen3/docs/gen3-resources/operator-guide/helm/helm-config-auth.md, gen3/docs/gen3-resources/operator-guide/helm/helm-config-data-svcs.md, gen3/docs/gen3-resources/operator-guide/helm/helm-config-frontend.md, gen3/docs/gen3-resources/operator-guide/helm/helm-config-revproxy.md, gen3/docs/gen3-resources/operator-guide/helm/helm-config-workspaces.md, gen3/docs/gen3-resources/operator-guide/helm/helm-deploy-databases.md, gen3/docs/gen3-resources/operator-guide/helm/helm-deploy-overview.md
=> add content to additional Helm docs (#279)

config.yaml, content/_index.md, content/products/_index.md, content/products/data-commons.md, content/products/data-hubs.md, content/products/data-meshes.md, content/products/mesh-services.md, content/products/workspaces.md, content/resources/_index.md
=> update product language and links

config.yaml, content/community/tutorials.md, layouts/shortcodes/events.html
=> create tutorials page and add videos

gen3/docs/gen3-resources/operator-guide/customize-search.md, gen3/docs/gen3-resources/operator-guide/submit-semi-structured-data.md
Link to JIRA ticket if there is one: 
For references to aggMDS, changed links from incorrect private repo to public MDS repo.
=> change links to AggMDS GitHub repo

layouts/partials/header.html
=> Add DD RUM to gen3.org website

layouts/partials/header.html
=> Disable sessionReplay for RUM

layouts/partials/header.html
=> Disable Datadog RUM for gen3.org

content/community/events.md, content/community/events/Users:.fileloc, content/community/events/gen3forum_20250507.md, content/community/events_archived.md
Link to JIRA ticket if there is one: 
Add new community forum
Moved some events to events archive page
=> update for data analysis community forum

content/community/events.md
=> publish may community forum

content/community/events.md, content/community/events/gen3forum_20250702.md
Link to JIRA ticket if there is one: 
Add a new event on July 2
=> Deployment community forum

content/community/events/gen3forum_20250702.md
=> Update Gen3 Forum Details
